// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    'intro',
    {
      type: 'doc',
       id: '0g',
      label: '0G',
    },
    {
      type: 'category',
      label: 'Gimo Finance',
      items: ['gimo-finance/st0g', 'gimo-finance/gimo_token'],
      collapsible: false,
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Architecture',
      items: ['architecture/gimo_architecture', 'architecture/ai_lsaas'],
      collapsible: false,
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'security/overview',
        // 'security/audit',
      ],
    },
    {
      type: 'category',
      label: 'Guide',
      items: ['guide/staking_a0gi_with_gimo', 'guide/contract_addresses'],
      collapsible: false,
      collapsed: false,
    },
  ],
};

export default sidebars;
