// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        {
          type: 'doc',
          id: 'intro',
          label: 'Gimo Finance',
        },
      '0g'],
      collapsible: false,
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Token',
      items: ['token/st0g', 'token/gimo_token', 'token/faucet', 'token/tokennomics'],
      collapsible: false,
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Architecture',
      items: ['architecture/gimo_architecture', 'architecture/staking_vault_architecture', 'architecture/ai_lsaas'],
      collapsible: false,
      collapsed: false,
    },
    'security/security',
    'roadmap/roadmap',
    // {
    //   type: 'category',
    //   label: 'Security',
    //   items: [
    //     'security/overview',
    //     // 'security/audit',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Guide',
    //   items: ['guide/staking_a0gi_with_gimo', 'guide/contract_addresses'],
    //   collapsible: false,
    //   collapsed: false,
    // },
  ],
};

export default sidebars;
